name: Code checks

on:
  push:
    branches: [master, homework]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run flake8
        run: flake8 .
      - name: Run mypy
        run: mypy new_app/
      - name: Run black
        run: black --diff --check .
      - name: Run isort
        run: isort --check-only --diff --profile black .
      - name: Run tests
        run: pytest tests/test__without_fixture.py


